import Head from "next/head";
import React, { ReactNode } from "react";
import Footer from "./Footer";
import Navbar from "./Navbar";
type Props = {
  children?: ReactNode;
  title?: string;
};

export default function Layout({ children, title }: Props) {
  const t = `${title} - Relative`;
  return (
    <>
      <Head>
        <title>{t}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      <Footer />
    </>
  );
}
